### ISSUE TITLE
Laravel 5 Support

### ISSUE THREAD

**Issue by mehrdd** [Devitek/laravel-yaml-translation#2]
Hi,
can i use yaml-translation in laravel 5 ?

thank you.

**Comment by CaporalDead** [comment]
Not yet but I'm working on it :), I'll keep you up to date ASAP.

2015-02-11 6:12 GMT+01:00 Mehrdad Nassiri <notifications@github.com>:

> Hi,
> can i use yaml-translation in laravel 5 ?
>
> thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Devitek/laravel-yaml-translation/issues/2>.
>



-- 
Thomas SIEFFERT
Ingénieur Informatique

« Le peuple n'a jamais eu autant de pouvoir que sur Internet. »
Valentin Lacambre

« Un grand pouvoir implique de grandes responsabilités. »
Benjamin Parker, Spider Man
________________________________

Adoptez l'éco-attitude.
N'imprimez ce mail que si c'est vraiment nécessaire

**Comment by mehrdd** [comment]
It would be nice !
Thank you ..

**Comment by unitedworx** [comment]
any updates on laravel-yaml-translation for L5 support? Seems that this one will need little modifications to work with L5 since Lang didnt change much, the hard one is going to be laravel-yaml-configuration since L5 loads configuration completely different from L4. Let me know if you have time to get them to work with L5 I am trying to move to L5 and i am missing only these 2 packages of yours. if you don have time i will be superb, if not then i will have to find another solution

**Comment by unitedworx** [comment]
just updated this for L5 compatibility and did a PR for it

**Comment by CaporalDead** [comment]
Yep thanks, didn't have the time/need to update it but your contributions are much appreciated :).
